Feature/page division range
evt-project/evt-viewer-angular pull request #110
Opened 2021-01-06 17:35 UTC by giuliac89

2021-01-11 15:33 UTC, szenzaro approved these changes

2021-01-12 17:11 UTC, ChiaraDipi requested changes
Just two minimum changes and we can merge

2021-01-12 17:11 UTC, ChiaraDipi commented on src/app/utils/dom-utils.ts
> +export function xpath(el: any): string { // TODO: get rid of any
Since any has been changed to string, you can remove the TODO

2021-01-12 17:11 UTC, ChiaraDipi commented on src/app/services/xml-parsers/structure-xml-parser.service.ts
> +
Remove useless line

2021-01-13 16:46 UTC, ChiaraDipi approved these changes

2021-01-13 16:46 UTC, merged