Feature/file desc visualization
evt-project/evt-viewer-angular pull request #162
Opened 2021-09-25 15:33 UTC by ChiaraDipi

Implementation of the component to visualize data retrieved from `<fileDesc>` element.
In order to test it, you can add
```
<evt-content-viewer [content]="testEl$ | async"></evt-content-viewer>
```
in `app.component.html` and 

```
public testEl$ = this.evtModelService.editionSource$.pipe(
  map(s => {
    const fileDesc = s.querySelector<HTMLElement>('fileDesc');
    const fileDescParser = createParser(FileDescParser, parse);

    return fileDescParser.parse(fileDesc);
  }),
  tap(e => console.log(e)),
);

constructor(
  private evtModelService: EVTModelService,
) {
}
```
in `app.component.ts` and of course have a complete `<fileDesc>` element in your TEI xml file.

2021-10-15 09:40 UTC, szenzaro requested changes

2021-10-15 09:40 UTC, szenzaro commented on src/app/components/extent/extent.component.html
> +<evt-header-section *ngIf="data?.content?.length > 0" [label]="'extent'" [additionalClass]="'extent'" [inlineLabel]="false">
Shouldn't the label be translated as well?

2021-10-15 09:40 UTC, szenzaro commented on src/app/components/publication-stmt/publication-stmt.component.html
> +        <ng-container *ngTemplateOutlet="section; context: { label: 'publisher', items: data?.publisher, class: 'publisher' }"></ng-container>
Shouldn't the labels be translated?

2021-10-15 09:40 UTC, szenzaro commented on src/app/components/series-stmt/series-stmt.component.html
> +            <ng-container *ngTemplateOutlet="section; context: { label: 'responsibles', items: data?.respStmt, class: 'respStmt', itemsSeparator: ', ' }"></ng-container>
Translate label

2021-10-15 09:40 UTC, szenzaro commented on src/app/components/series-stmt/series-stmt.component.html
> +    <evt-header-section *ngIf="items?.length > 0" [label]="label" [additionalClass]="class" [inlineLabel]="true">
translate label

2021-10-15 09:40 UTC, szenzaro commented on src/app/components/title-stmt/title-stmt.component.html
> +<ng-container *ngTemplateOutlet="section; context: { label: 'editors', items: data?.editors, class: 'editor' }"></ng-container>
labels need transaltion

2021-10-15 09:40 UTC, szenzaro commented on src/app/components/edition-stmt/edition-stmt.component.html
> +        <ng-container *ngTemplateOutlet="section; context: { label: 'edition', items: data?.edition, class: 'edition' }"></ng-container>
Translate labels

2021-11-03 12:41 UTC, szenzaro approved these changes

2021-12-04 15:00 UTC, giuliac89 approved these changes

2021-12-04 15:02 UTC, merged