Feature/encoding desc vizualization
evt-project/evt-viewer-angular pull request #170
Opened 2021-12-13 15:15 UTC by ChiaraDipi

First part of encoding description visualization. 
Elements handled in a specific way are
- Project description (`<projectDesc>`)
- Sampling declaration (`<samplingDecl>`)
- Editorial declaration (`<editorialDecl>`)
- Rendition (`<rendition>`)
- Namespace (`<namespace>`)
- Tags declaration (`<tagsDecl>`)

Other elements of encoding description are still rendered with generic element and will be handled in a separate PR

2021-12-18 19:00 UTC, giacomocerre commented on src/app/components/encoding-desc/encoding-desc.component.spec.ts
> +
Remove space

2021-12-18 19:02 UTC, giacomocerre commented on src/app/components/project-desc/project-desc.component.spec.ts
> +
Remove space

2021-12-18 19:02 UTC, giacomocerre commented on src/app/components/sampling-decl/sampling-decl.component.spec.ts
> +
Remove space

2021-12-18 19:02 UTC, giacomocerre commented on src/app/components/editorial-decl/editorial-decl.component.spec.ts
> +
Remove space

2021-12-18 19:06 UTC, giacomocerre commented on src/app/components/rendition/rendition.component.scss
> +
Remove space

2021-12-18 19:06 UTC, giacomocerre commented on src/app/components/rendition/rendition.component.spec.ts
> +
Remove space

2021-12-18 19:06 UTC, giacomocerre commented on src/app/components/namespace/namespace.component.spec.ts
> +
Remove space

2021-12-18 19:06 UTC, giacomocerre commented on src/app/components/tags-decl/tags-decl.component.spec.ts
> +
Remove space

2021-12-18 19:06 UTC, giacomocerre commented on src/app/components/encoding-desc/encoding-desc.component.spec.ts
> +
Remove space

2021-12-18 19:06 UTC, giacomocerre commented on src/app/components/project-desc/project-desc.component.spec.ts
> +
Remove space

2021-12-18 19:06 UTC, giacomocerre commented on src/app/components/sampling-decl/sampling-decl.component.spec.ts
> +
Remove space

2021-12-18 19:06 UTC, giacomocerre commented on src/app/components/editorial-decl/editorial-decl.component.spec.ts
> +
Remove space

2022-01-04 15:59 UTC, giuliac89 commented
Resolve conflict

2022-01-04 15:59 UTC, giuliac89 requested changes

2022-01-04 15:59 UTC, giuliac89 commented on src/app/components/editorial-decl/editorial-decl.component.html
> +
Remove space

2022-01-11 16:33 UTC, szenzaro approved these changes

2022-01-11 16:56 UTC, ChiaraDipi commented on CHANGELOG.md
> +- Encoding description visualization
Next time

2022-01-17 10:00 UTC, szenzaro approved these changes

2022-01-27 17:29 UTC, giuliac89 approved these changes

2022-01-27 17:29 UTC, merged