Feature/annotator selection text
evt-project/evt-viewer-angular pull request #91
Opened 2020-10-04 10:03 UTC by giacomocerre

2020-10-06 09:03 UTC, ChiaraDipi requested changes
Can you generalize the `@HostListener('mouseup')` part in order to avoid code duplication? You could try using a directive

2020-10-06 20:34 UTC, ChiaraDipi requested changes

2020-10-06 20:34 UTC, ChiaraDipi commented on src/app/panels/sources-panel/sources-panel.component.html
> +<evt-panel evtAnnotator [secondary]="true">
I would put the `evtAnnotator` directive in the content div, so that the annotator works only on text and not on tools in the header/footer

2020-10-06 20:34 UTC, ChiaraDipi commented on src/app/panels/text-panel/text-panel.component.html
> +<evt-panel evtAnnotator [showSecondaryContent]="isSecondaryContentOpened()">
Same as previous comment

2020-10-06 20:34 UTC, ChiaraDipi commented on src/app/panels/version-panel/version-panel.component.html
> +<evt-panel evtAnnotator [comparable]="true" [secondary]="true" [closable]="true" (hide)="emitHide()">
Same as previous comment

2020-10-06 20:34 UTC, ChiaraDipi commented on src/app/panels/witness-panel/witness-panel.component.html
> +<evt-panel evtAnnotator [comparable]="true" [secondary]="true" [closable]="true" (hide)="emitHide()">
Same as previous comment

2020-10-09 08:18 UTC, szenzaro requested changes

2020-10-09 08:18 UTC, szenzaro commented on src/app/services/annotator/annotator.service.ts
> +  textSelection = new Subject();
Missing type for this subject. What is the type of `textSelection`?

2020-12-01 09:33 UTC, szenzaro submitted a review, later dismissed

2020-12-01 09:33 UTC, szenzaro commented on src/app/services/annotator/annotator.service.ts
> +  textSelection: Subject<object> = new Subject();
is the `textSelection` just an `object`?

2020-12-01 09:33 UTC, szenzaro commented on src/app/services/annotator/annotator.service.ts
> +    const selection = window.getSelection();
no need of this variable declaration

2020-12-01 09:33 UTC, szenzaro commented on src/app/services/annotator/annotator.service.ts
> +  getTextSelection() {
the name suggests you return something, but you do not.
Either change the name or return te text selection

2020-12-01 09:33 UTC, szenzaro commented on src/app/services/annotator/annotator.service.ts
> +    console.log(this.textSelection);
remove `console.log`

2020-12-01 09:33 UTC, szenzaro commented on src/app/services/annotator/annotator.service.ts
> +  textSelection: Subject<object> = new Subject();
it seems that this can be written as `textSelection = new Subject<Selection>();`

2021-03-29 07:55 UTC, giuliac89 requested changes

2021-03-30 06:07 UTC, giuliac89 approved these changes

2021-03-30 06:11 UTC, merged